version: '3.8'


services: 

    loadbalancer:
        build: ./nginx
        restart: always
        ports: 
            - "80:80"
        networks: 
            - network

    db:
        image: mongo
        restart: always
        environment: 
            MONGO_INITDB_ROOT_USERNAME: express-user
            MONGO_INITDB_ROOT_PASSWORD: password_is_tough
        
        volumes: 
            - ./database:/data/db
        networks:
            - network
        

    
    backend:
        build: ./backend-API
        restart: on-failure
        volumes: 
            - ./backend-API:/app
        networks:
            - network
        depends_on: 
            - db
            - loadbalancer

networks: 
    network:
        driver: bridge
